services:
  db:
    image: postgres:14
    container_name: notes_db
    env_file: .env
    volumes:
      - notes_db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - notes_network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - notes_network
    

volumes:
  notes_db:
    external: true

networks:
  notes_network:
    external: true