"""delete orphan added

Revision ID: 94cc8f2cb5c0
Revises: 5ec025d4fd70
Create Date: 2024-02-27 01:01:20.819844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94cc8f2cb5c0'
down_revision: Union[str, None] = '5ec025d4fd70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
