"""change in database

Revision ID: c8401cca5d19
Revises: 
Create Date: 2024-02-21 13:27:36.428923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8401cca5d19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('user_account', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('user_account', 'username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_account', 'username',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('user_account', 'last_name',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('user_account', 'first_name',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
